name: AWS Integration Tests

on:
  workflow_call:
    inputs:
      aws-region:
        default: 'us-east-1'
        required: false
        type: string

    secrets:
      BOT_AWS_ACCESS_KEY_ID:
        required: true
      BOT_AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  aws-deploy:
    name: AWS Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/test-integration-run-one
        with:
          integration-test: aws-deploy
          aws-region: ${{ inputs.aws-region }}
          bot-aws-access-key-id: ${{ secrets.BOT_AWS_ACCESS_KEY_ID }}
          bot-aws-secret-access-key: ${{ secrets.BOT_AWS_SECRET_ACCESS_KEY }}

  aws-integration-tests:
    strategy:
      max-parallel: 1
      matrix:
        integration-test: [aws-func, aws-end-to-end, aws-load]
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/test-integration-run-one
        with:
          integration-test: ${{ matrix.integration-test }}
          aws-region: ${{ inputs.aws-region }}
          bot-aws-access-key-id: ${{ secrets.BOT_AWS_ACCESS_KEY_ID }}
          bot-aws-secret-access-key: ${{ secrets.BOT_AWS_SECRET_ACCESS_KEY }}

  aws-nuke:
    name: AWS Nuke
    needs: [aws-deploy]
    if: always() && needs.aws-deploy.result == 'success'
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/test-integration-run-one
        with:
          integration-test: aws-nuke
          aws-region: ${{ inputs.aws-region }}
          bot-aws-access-key-id: ${{ secrets.BOT_AWS_ACCESS_KEY_ID }}
          bot-aws-secret-access-key: ${{ secrets.BOT_AWS_SECRET_ACCESS_KEY }}
